<table style="width:100%;">
    <tr style="display:none">
        <td></td>
        <td></td>
    </tr>
    <tr style="height:3em">
        <td style="width:20%;align:left"><img src="logo_iutR&T.jpg"></td>
        <td style="width:60%;font: bold 2.5em 'Fira Sans', serif;text-align:center"> SAE 204<br> Projet Intégratif
       </td>
        <td style="width:20%;font: bold 1.3em 'Fira Sans', serif;vertical-align:top;text-align:center"><br>Documentation<br> <i>Rapport de projet</i></td>
    </tr>
</table>

L'objectif de  ce TP est de résoudre des systèmes linéaires par la méthode de Gauss. On se donne le sytème suivant qui admet une solution unique et qui nous servira d'exemple.

$$(S)\begin{cases}
x+2y-5z & =1 \\
2x+3y+z & =4 \\
x-y+5z & =6 \\
\end{cases}$$





Pour la résolution du système d'équations, on passe  par la matrice augmentée qui représente ce système.

$$(S)\begin{pmatrix}
1 & 2 & -5  & 1 \\
2 & 3 & 1 & 4 \\
1 & -1 & 5 & 6 \\
\end{pmatrix}$$


Dans toute la suite, on utilisera la bibliothèque `numpy`, disponible par l'alias np.
```python
import numpy as np
```
Tester et commenter les lignes suivantes.

In [1]:
import numpy as np

M=np.array([[1.0,2,-5,1],[2,3,1,4],[1,-1,5,6]],dtype=float)
print(M)
print(M[1,1])
print(M[1])
print(M[:,2])
print(M.shape)
print(M.shape[0])
print(M.shape[1])
# Pour échanger le contenu des variables a et b
a,b=2,3
b,a=a,b
print(a,b)

[[ 1.  2. -5.  1.]
 [ 2.  3.  1.  4.]
 [ 1. -1.  5.  6.]]
3.0
[2. 3. 1. 4.]
[-5.  1.  5.]
(3, 4)
3
4
3 2



### Fonctions utiles

1) Ecrire la fonction permutation(M,i1,i2) et vérifier que cette fonction donne les résultats attendus. 



In [6]:
def permutation(A,i1,i2):
    for a in range(A.shape[1]):
        A[i1,a],A[i2,a]=A[i2,a],A[i1,a]
    return A
   
M=np.array([[1.0,2,-5,1],[2,3,1,4],[1,-1,5,6]],dtype=float)
print(M)
permutation(M,0,2)
print(M)
    

[[ 1.  2. -5.  1.]
 [ 2.  3.  1.  4.]
 [ 1. -1.  5.  6.]]
[[ 1. -1.  5.  6.]
 [ 2.  3.  1.  4.]
 [ 1.  2. -5.  1.]]


2. Ecrire une fonction dilatation(A,i,k) qui effectue l'opération élémentaire $L_i \leftarrow k\times L_i$

In [8]:
def dilatation(A,i,k):
    for a in range(A.shape[1]):
        A[i,a]=A[i,a]*k
    return A

M=np.array([[1.0,2,-5,1],[2,3,1,4],[1,-1,5,6]],dtype=float)
dilatation(M,0,3)
print(M)

[[  3.   6. -15.   3.]
 [  2.   3.   1.   4.]
 [  1.  -1.   5.   6.]]


3. Ecrire une fonction transvection(A,i,j,k) qui effectue l'opération $L_i \leftarrow L_i+k\times L_j$

In [9]:
def transvection(A,i,j,k):
    for a in range(A.shape[1]):
        A[i,a]=A[i,a]+k*A[j,a]
    return A

M=np.array([[1.0,2,-5,1],[2,3,1,4],[1,-1,5,6]],dtype=float)
print(M)
transvection(M,1,0,-2)
print(M)

[[ 1.  2. -5.  1.]
 [ 2.  3.  1.  4.]
 [ 1. -1.  5.  6.]]
[[ 1.  2. -5.  1.]
 [ 0. -1. 11.  2.]
 [ 1. -1.  5.  6.]]


4. En utilisant ces fonctions, rendre le sytème échelonné puis mettre des 1 sur la diagonale. En déduire l'ensemble des solutions de ce sytème.

In [18]:
M=np.array([[1.0,2,-5,1],[2,3,1,4],[1,-1,5,6]],dtype=float)
print(M)
transvection(M,1,0,-2)
transvection(M,2,0,-1)
transvection(M,2,1,-3)
dilatation(M,1,-1)
dilatation(M,2,-1/23)
print(M)

[[ 1.  2. -5.  1.]
 [ 2.  3.  1.  4.]
 [ 1. -1.  5.  6.]]
[[  1.           2.          -5.           1.        ]
 [ -0.           1.         -11.          -2.        ]
 [ -0.          -0.           1.           0.04347826]]


L'objectif est maintenant de programmer cette recherche de solution par le pivot.

### Etape 1 :  Echelonner la matrice

1. Ecrire une fonction zeros_bas() qui admet en entrée une matrice M et un entier i et qui renvoie la matrice équivalente M comportant des zéros sous le pivot M[i,i] (on suppose que ce pivot n'est pas nul).  
Tester la fonction pour le premier pivot : i = 0.



In [42]:
def zero_bas(M,i):
    assert M[i,i]!=0
    dilatation(M,i,1/M[i,i])
    for a in range(i+1,M.shape[0]):
        transvection(M,a,i,-M[a,i])
    return M

M=np.array([[1,2,-5,1],[2,3,1,4],[1,-1,5,6]], dtype=float)
zero_bas(M,0)
zero_bas(M,1)
zero_bas(M,2)

print(M)


[[  1.           2.          -5.           1.        ]
 [ -0.           1.         -11.          -2.        ]
 [ -0.          -0.           1.           0.04347826]]


2. Ecrire une fonction echelonner() qui admet la matrice M en entrée et renvoie la matrice échelonnée M (cette fonction fait appel à la fonction zeros_bas()).  
Tester votre fonction.

In [45]:
def echelonner(M):
    for a in range(M.shape[0]):
        zero_bas(M,a)
    return M

        
M=np.array([[1,2,-5,1],[2,3,1,4],[1,-1,5,6]])
echelonner(M)
print(M)

[[  1   2  -5   1]
 [  0   1 -11  -2]
 [  0   0   1   0]]




### Etape 2 : Réduire

1) Ecrire une fonction zeros_haut() qui admet une matrice  M et un entier i en entrée et renvoie une matrice M avec des zéros sur la colonne au-dessus du pivot M[i,i].


In [1]:
def zero_haut(M,i):
    assert M[i,i]!=0
    dilatation(M,i,1/M[i,i])
    for a in range(i-1,-1,-1):
        transvection(M,a,i,-M[a,i])
    return M



M=np.array([[1,2,-5,1],[2,3,1,4],[1,-1,5,6]],dtype=float)
zero_haut(M,2)
print(M)


NameError: name 'np' is not defined

2. Ecrire une fonction reduire() qui admet une matrice échelonnée réduite M en entrée et renvoie une matrice M dont la partie gauche est une diagonale de 1.(matrice identité)

In [75]:
def reduire(M):
    for a in range(M.shape[0]-1,-1,-1):
        zero_haut(M,a)
    return M
   

M=np.array([[1,2,-5,1],[2,3,1,4],[1,-1,5,6]],dtype=float)  
reduire(M)
print(M)


[[ 1.          0.          0.          4.26086957]
 [ 0.5625      1.          0.          0.875     ]
 [ 0.2        -0.2         1.          1.2       ]]


### Conclusion

En déduire une fonction pivot() qui applique l'algorithme du pivot à la matrice M et retourne la solution du système.

In [77]:

def pivot(M):
  echelonner(M)
  reduire(M)
  return M
    
M=np.array([[1,2,-5,1],[2,3,1,4],[1,-1,5,6]],dtype=float)
print(pivot(M))

[[ 1.          0.          0.          4.26086957]
 [-0.          1.          0.         -1.52173913]
 [-0.         -0.          1.          0.04347826]]


### une fonction native

La bibliothèque numpy possède déjà une fonction permettant de résoudre des systèmes linéaires 'linalg.solve'.  
Lire la documentation de cette fonction et retrouver le résultat précédent.